---
title: "Syllabus"
---

## Course info

|           | Day       | Time              | Location |
|-----------|-----------|-------------------|----------|
| Lecture   | Tuesday    | 08:15  - 09:45 am  |  [016b](https://horst.hdm-stuttgart.de/171)  |


:::{.callout-important}
Note that there are additional lectures (see schedule at [StarPlan](https://splan.hdm-stuttgart.de/splan/))
:::

## Learning objectives

By the end of this module, students are able to:

- Understand statistical terms and concepts
- Recognize patterns in data
- Create effective charts and visualizations
- Develop predictive models
- Clearly and effectively communicate statistical results
- Utilize modern tools and technologies (like Generative AI) for data analysis

## Where to get help

- If you have a question during lecture, feel free to ask it! 
- Outside of class, any general questions about course content or assignments should be posted on the Moodle course forum.
- Emails should be reserved for questions not appropriate for the public forum. **If you email me, please include the name of our course in the subject line.** 

Check out the [Support](course-support.qmd) page for more resources.

## Textbooks

This course is mainly based on the following book:

[Çetinkaya-Rundel, M. & Hardin, J (2023). Introduction to Modern Statistics. OpenIntro. Inc.](https://openintro-ims.netlify.app/)

## Exams {#sec-exams}

There will be one exam. More details about the exams will be given during the semester.

